# Generated by Django 4.2.1 on 2023-05-06 22:27

import ars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_object', models.IntegerField(verbose_name='Номер объекта (ID)')),
                ('name', models.CharField(max_length=300, verbose_name='Название Объекта')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('description', models.TextField(verbose_name='Описание объекта')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('contractor', models.CharField(max_length=60, verbose_name='Генеральный подрядчик')),
                ('customer', models.CharField(max_length=60, verbose_name='Заказчик')),
                ('designer', models.CharField(max_length=60, verbose_name='Проектировщик')),
                ('types_of_work', models.CharField(max_length=150, verbose_name='Виды выполняемых работ')),
                ('building_area', models.CharField(max_length=50, verbose_name='Площадь застройки')),
                ('data', models.DateTimeField(verbose_name='Окончание строительства')),
                ('photo', models.FileField(upload_to=ars.models.png_save, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
